#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..."
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..."

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE DATA DIR
#=================================================

# Remove the data directory if --purge option is used
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
	ynh_script_progression --message="Removing app data directory..."
	ynh_secure_remove --file="$data_dir"
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..."

# Remove metapackage and its dependencies
apt-get -y remove --purge rport-guacamole

#=================================================
# CLOSE A PORT
#=================================================

if yunohost firewall list | grep -q "\- $port_client$"
then
	ynh_script_progression --message="Closing port $port_client..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port_client
fi

if yunohost firewall list | grep -q "\- $port_used_start:$port_used_end$"
then
	ynh_script_progression --message="Closing port $port_used_start:$port_used_end..."
	ynh_exec_warn_less yunohost firewall disallow TCP $port_used_start:$port_used_end
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

# Remove the log files
ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
